/* Generated By:JavaCC: Do not edit this line. SwarmerParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SwarmerParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DECIMAL = 33;
  /** RegularExpression Id. */
  int NUMBER = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int VALUE = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"views\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"size\"",
    "\";\"",
    "\"entities\"",
    "\",\"",
    "\"view_shape\"",
    "\"entity\"",
    "\"attributes\"",
    "\"behaviours\"",
    "\"behaviour\"",
    "\"view\"",
    "\"operation\"",
    "\"attribute\"",
    "\"panic\"",
    "\"true\"",
    "\"false\"",
    "\"flank\"",
    "\"field\"",
    "\"closest\"",
    "\"average\"",
    "\"wander\"",
    "\"force\"",
    "\"position\"",
    "\"vector\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 32>",
    "<DECIMAL>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<VALUE>",
  };

}
